### ISSUE TITLE
Add a "Short URL to this page" buttom

### ISSUE THREAD

**Issue by labra** [weso/rdfshape#28]
It would be very useful to have some kind of URL shortener which would allow to copy/paste links to RDFShape examples easily.

An inspiration would be the buttom provided by the wikimedia query service. I think it uses a [URL shortener service](https://meta.wikimedia.org/wiki/Special:UrlShortener). 

And the source code seems to be [here](https://github.com/wikimedia/mediawiki-extensions-UrlShortener). 

I am also guessing that the URL shortener service uses a database to store the shortened URLs. 

There is some background on URL shortening in [stackoverflow](https://stackoverflow.com/questions/742013/how-do-i-create-a-url-shortener) which contains several implementations.

**Comment by ulitol97** [comment]
Closing due to a permalink service being already implemented (ref: [https://github.com/weso/rdfshape/pull/195](https://github.com/weso/rdfshape/pull/195)).
