### ISSUE TITLE
Multibyte char in response is garbled

### ISSUE THREAD

**Issue by eggplants** [weso/rdfshape#29]
In <https://rdfshape.herokuapp.com/query>, Multibyte char (especially kanji) contains of response text is garbled by wrong encoding.

## Screenshot

![image](https://user-images.githubusercontent.com/42153744/147836789-efd744f0-792c-4c20-9580-c46104ca6671.png)

## RDF Data

- By Endpoint: <https://ja.dbpedia.org/sparql>

## Query

```rq
# This query looks up names and codes of prefectures in Japan.
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://ja.dbpedia.org/resource/>
PREFIX dbprop: <http://ja.dbpedia.org/property/>
select ?pref ?code
where {
  ?pref
    dc:subject dbr:Category:日本の都道府県;
    dbprop:区分 ?category;
    dbo:areaCode ?code.
  filter regex(?category, "[都道府県]")
  filter regex(?code, "JP")
} order by ?pref limit 10
```

**Comment by labra** [comment]
Thanks a lot for using RDFShape and for your report. 

We will try to reproduce and check where is the error...I guess it is related to how we support encodings when we submit the query. 

By the way, I recommend you to try http://rdfshape.weso.es instead of the heroku one. Although both are the same software, the heroku one is a free service and when we surpass the allowed free usage, it goes down...while rdfshape is deployed from a more stable server.

**Comment by eggplants** [comment]
Thank you for your support!
I tried to query on your site, but it is not worked well.

[Query URL](https://rdfshape.weso.es/endpointQuery?activeQueryTab=%23queryTextArea&endpoint=https%3A%2F%2Fja.dbpedia.org%2Fsparql&query=PREFIX%20dc%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0APREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fja.dbpedia.org%2Fresource%2F%3E%0APREFIX%20dbprop%3A%20%3Chttp%3A%2F%2Fja.dbpedia.org%2Fproperty%2F%3E%0Aselect%20%3Fpref%20%3Fcode%0Awhere%20%7B%0A%20%20%3Fpref%0A%20%20%20%20dc%3Asubject%20dbr%3ACategory%3A%E6%97%A5%E6%9C%AC%E3%81%AE%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%3B%0A%20%20%20%20dbprop%3A%E5%8C%BA%E5%88%86%20%3Fcategory%3B%0A%20%20%20%20dbo%3AareaCode%20%3Fcode.%0A%20%20filter%20regex%28%3Fcategory%2C%20%22%5B%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%5D%22%29%0A%20%20filter%20regex%28%3Fcode%2C%20%22JP%22%29%0A%7D%20order%20by%20%3Fpref%20limit%2010)

![image](https://user-images.githubusercontent.com/42153744/147911402-cba8606d-6d48-4eae-a2d5-63ca28ac7482.png)

```text
Error calling server at https://api.rdfshape.weso.es/api/endpoint/query: Error: Network Error. Did you input a valid SPARQL endpoint and query?
```

worked well on Yasgui - <https://api.triplydb.com/s/tanIKOK6k>

**Comment by mistermboy** [comment]
Hi @eggplants! Thanks for the report. I'm afraid we are having some problems with the rdfshape api recently. Now it should be working again.

**Comment by eggplants** [comment]
![Uploading image.png…]()
Thanks!
