### ISSUE TITLE
Error doing POST request to http://rdfshape.weso.es:8080/api/schema/visualize: Error: Network Error

### ISSUE THREAD

**Issue by thewilly** [weso/rdfshape#98]
While trying the following shape I got this error:
`Error doing POST request to http://rdfshape.weso.es:8080/api/schema/visualize: Error: Network Error`

![imagen](https://user-images.githubusercontent.com/10364506/80699601-8d858f00-8adc-11ea-97b0-3efb57067890.png)

Any hint?

**Comment by labra** [comment]
I tried it and it works for me: 

https://tinyurl.com/ycmfz7xm

Could it be a temporary error?

By the way the first shape:

```
:User {
 a :Person 
}
```

is probably wrong, it should probably be:

```
:User {
 a [ :Person ]
}
```

**Comment by thewilly** [comment]
Yes now it works for me too, you can close this issue 🙃. Regarding the shape I was just trying out things about with the ‘a’ keyword. Thanks.
